### ISSUE TITLE
Check that search is working

### ISSUE THREAD

**Issue by nimbinatus** [rackerlabs/rackspace-whitepapers#20]

**Comment by catlook** [comment]
Magic 8 ball says "mixed results".  I searched for "cloud economics" and search gave me the whitepapers home page (where cloud economics article is featured). It did not give me the paper itself.  And when i searched for "six red marbles", which is a company in one of the use cases, I got noting at all.  A search on "Cloud Servers" likewise did not show any whitepapers.  A search for "Cloud Servers white" brought up the whitepaper landing page (but no actual whitepapers) and other how-to or developer links.

**Comment by nimbinatus** [comment]
Search now appears to be working. A search for "makita" brings up the whitepaper for Makita. Probably just needed time to index.
